//Configuration for YTPlayer
//Automatically Generated by PhantomBot at Startup
//Do NOT Modify! Overwritten when PhantomBot is restarted!
var playerPort = 25003;
var channelName = "thefirstnoob_twitch";
var auth="5clf5gLj0Z8zXA3SVOPAwgvmMN0VeA";
var http="http://";
function getPlayerPort() { return playerPort; }
function getChannelName() { return channelName; }
function getAuth() { return auth; }
function getProtocol() { return http; }
